name: CI-nightly
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - t=${{ matrix.threads }} - jet=${{ matrix.jet }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - nightly
        os:
          - ubuntu-latest
        threads:
          - '1'
        jet:
          - 'true'
          - 'false'
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Install and Test
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          pkg"dev . ./QSymbolicsBase ./QSymbolicsClifford ./QSymbolicsOptics"
          Pkg.test("QSymbolics"; coverage=true)
        env:
          JULIA_NUM_THREADS: ${{ matrix.threads }}
          QSYMBOLICS_JET_TEST: ${{ matrix.jet }}
      - uses: julia-actions/julia-processcoverage@v1
#      - uses: julia-actions/julia-uploadcoveralls@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
